# Generated by Django 3.2.3 on 2021-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('thoughts_app', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='login_app.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
